export default function TermsOfServicePage() {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 20px', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
      <h1>Terms of Service</h1>
      <p style={{ fontSize: '14px', color: '#999' }}>Last updated: October 23, 2025</p>

      <h2 style={{ marginTop: '30px' }}>1. Acceptance of Terms</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        By accessing or using PrepMyMeeting ("Service"), you agree to be bound by these Terms of Service
        ("Terms"). If you do not agree to these Terms, do not use the Service.
      </p>

      <h2 style={{ marginTop: '30px' }}>2. Description of Service</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        PrepMyMeeting is an AI-powered meeting preparation assistant accessible via WhatsApp and Telegram.
        The Service provides:
      </p>
      <ul style={{ fontSize: '16px', lineHeight: '1.8', color: '#555' }}>
        <li>Personalized meeting preparation checklists</li>
        <li>Voice message transcription</li>
        <li>Web search for real-time information</li>
        <li>Calendar integration for proactive meeting reminders (optional)</li>
        <li>Customizable response preferences</li>
      </ul>

      <h2 style={{ marginTop: '30px' }}>3. Eligibility</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        You must be at least 13 years old to use this Service. By using the Service, you represent and
        warrant that you meet this age requirement.
      </p>

      <h2 style={{ marginTop: '30px' }}>4. User Accounts and Responsibilities</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        When you use PrepMyMeeting, you agree to:
      </p>
      <ul style={{ fontSize: '16px', lineHeight: '1.8', color: '#555' }}>
        <li>Provide accurate information</li>
        <li>Keep your account secure</li>
        <li>Use the Service only for lawful purposes</li>
        <li>Not attempt to gain unauthorized access to the Service</li>
        <li>Not use the Service to spam, harass, or harm others</li>
        <li>Not violate any applicable laws or regulations</li>
      </ul>

      <h2 style={{ marginTop: '30px' }}>5. Acceptable Use</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        You may not use the Service to:
      </p>
      <ul style={{ fontSize: '16px', lineHeight: '1.8', color: '#555' }}>
        <li>Share illegal, harmful, or offensive content</li>
        <li>Impersonate others or provide false information</li>
        <li>Distribute malware or engage in phishing</li>
        <li>Violate intellectual property rights</li>
        <li>Attempt to reverse engineer or exploit the Service</li>
        <li>Use automated tools to access the Service without permission</li>
      </ul>

      <h2 style={{ marginTop: '30px' }}>6. AI-Generated Content</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        The meeting preparation content generated by PrepMyMeeting is created using artificial intelligence
        and is provided for informational purposes only. We do not guarantee the accuracy, completeness,
        or suitability of the AI-generated content. You should review and verify all suggestions before
        using them in professional or personal settings.
      </p>

      <h2 style={{ marginTop: '30px' }}>7. Third-Party Services</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        Our Service integrates with third-party platforms including WhatsApp, Telegram, OpenAI, Perplexity AI,
        and Google Calendar. Your use of these platforms is subject to their respective terms of service
        and privacy policies.
      </p>

      <h2 style={{ marginTop: '30px' }}>8. Data and Privacy</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        Your use of the Service is also governed by our{' '}
        <a href="/privacy" style={{ color: '#0066cc' }}>Privacy Policy</a>. We collect and process
        your data as described in the Privacy Policy.
      </p>

      <h2 style={{ marginTop: '30px' }}>9. Intellectual Property</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        The Service, including its design, functionality, and content (excluding user-generated content),
        is owned by PrepMyMeeting and protected by intellectual property laws. You may not copy, modify,
        distribute, or create derivative works without our permission.
      </p>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        You retain ownership of the content you submit to the Service. By using the Service, you grant us
        a license to process your content to provide the Service.
      </p>

      <h2 style={{ marginTop: '30px' }}>10. Limitation of Liability</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, PREPMYMEETING SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
        WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER
        INTANGIBLE LOSSES.
      </p>

      <h2 style={{ marginTop: '30px' }}>11. Disclaimer of Warranties</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER
        EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>

      <h2 style={{ marginTop: '30px' }}>12. Service Availability</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        We strive to keep the Service available 24/7, but we do not guarantee uninterrupted access.
        We may modify, suspend, or discontinue the Service at any time without notice.
      </p>

      <h2 style={{ marginTop: '30px' }}>13. Termination</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        We reserve the right to terminate or suspend your access to the Service at any time, with or
        without cause or notice. You may stop using the Service at any time and request deletion of
        your data via our{' '}
        <a href="/data-deletion" style={{ color: '#0066cc' }}>Data Deletion page</a>.
      </p>

      <h2 style={{ marginTop: '30px' }}>14. Changes to Terms</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        We may update these Terms from time to time. Continued use of the Service after changes
        constitutes acceptance of the new Terms. We will post the updated Terms with a new
        "Last updated" date.
      </p>

      <h2 style={{ marginTop: '30px' }}>15. Governing Law</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        These Terms shall be governed by and construed in accordance with the laws of your jurisdiction,
        without regard to its conflict of law provisions.
      </p>

      <h2 style={{ marginTop: '30px' }}>16. Contact Information</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        If you have any questions about these Terms, please contact us at:{' '}
        <a href="mailto:enevoldsen.j@gmail.com" style={{ color: '#0066cc' }}>
          enevoldsen.j@gmail.com
        </a>
      </p>

      <h2 style={{ marginTop: '30px' }}>17. Severability</h2>
      <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#555' }}>
        If any provision of these Terms is found to be unenforceable or invalid, that provision shall
        be limited or eliminated to the minimum extent necessary, and the remaining provisions shall
        remain in full force and effect.
      </p>

      <hr style={{ margin: '40px 0', border: 'none', borderTop: '1px solid #ddd' }} />

      <p style={{ fontSize: '14px', color: '#999', textAlign: 'center' }}>
        PrepMyMeeting - Your AI Meeting Preparation Assistant
      </p>
    </div>
  );
}
